# ==============================
# Server configurations
# ==============================
server:
  port: 8080
  servlet:
    context-path: /gngsb
    
# ==============================
# Database configurations
# ==============================
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          lob:
            '[non_contextual_creation]': true # 실행 시 Warning 제거
    hibernate:
      # create : 기존 테이블 삭제 후 재생성
      # create-drop : create + 종료시점에 테이블 삭제
      # update : 변경분만 반영
      # validate : 엔티티와 테이블 정상 매핑만 확인
      # none : 사용하지 않음
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  output:
    ansi:
      enabled: always
# ==============================
# Email configurations
# ==============================
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true # 사용자 인증 시도
          starttls: # StartTLS 활성화
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
            protocols: TLSv1.2
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

mail:
  token:
    valid-time: 5

# ==============================
# Jasypt configurations
# ==============================
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    key-obtention-iterations: 1000
    pool-size: 1
    provider-name: SunJCE
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    string-output-type: base64

# ==============================
# Common configurations
# ==============================
application:
  name: GNGSB
  version: 1.0.0